# Generated by Django 4.2.16 on 2025-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_missing_fields_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='news_articl_publica_3ddb49_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='news_articl_status_a95c4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='news_articl_categor_ac462d_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='show_breaking_image',
            field=models.BooleanField(default=True, help_text='Show article image in breaking news banner'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='news_articl_status_dad29a_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='news_articl_categor_846014_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', 'status'], name='news_articl_is_feat_7a10f2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-views_count'], name='news_articl_views_c_c4cc27_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-views_count'], name='news_articl_status_0937d3_idx'),
        ),
    ]
