# Generated by Django 4.2.16 on 2025-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_show_breaking_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show_breaking_image',
            field=models.BooleanField(default=False, help_text='Show article image in breaking news banner'),
        ),
    ]
